import '../style/global.css';
import './globals.css'
import StyledComponentsRegistry from '@/lib/registry'

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <StyledComponentsRegistry>
      <body>{children}</body>
      </StyledComponentsRegistry>
    </html>
  );
}
