"use client";
import "../style/global.css";
import "./globals.css";
import StyledComponentsRegistry from "@/lib/registry";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import { green, orange } from "@mui/material/colors";
import { theme } from "@/constants/theme";
const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// const theme = createTheme({

//   palette: {
//     primary: {
//       main: orange[500],
//     },
//   },
// });
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <ThemeProvider theme={theme}> */}
      <StyledComponentsRegistry>
        <body>{children}</body>
      </StyledComponentsRegistry>
      {/* </ThemeProvider> */}
    </html>
  );
}
